In [1]:
import pandas as pd
import numpy as np 
import matplotlib as plt
import sklearn as sl
import os

In [ ]:
#Exporting the data
folder_path = r"C:\Users\USER\Desktop\final readings\2.5 feet readings"  # your folder path

all_data = []

for file in os.listdir(folder_path):
    if file.endswith(".xlsx"):
        file_path = os.path.join(folder_path, file)
        df = pd.read_excel(file_path)
        all_data.append(df)

# Combine all files into one DataFrame
combined_df = pd.concat(all_data, ignore_index=True)

print(combined_df.shape)

(3641386, 9)

In [5]:
combined_df.describe()

,Frequency(Hz),Magnitude(db),Phase(degrees),Angle of turn table,x,y,z,Distance,Frequency(KHz)
count,3.641385e+06,3.641385e+06,3.641385e+06,3.641385e+06,3.641385e+06,3.641385e+06,3.641385e+06,3.388506e+06,230472.000000
mean,9.999584e+09,2.145154e+03,1.193293e+00,1.693829e+02,1.483620e+00,5.477700e+00,1.176021e+00,6.083500e+00,10.000012
std,1.155033e+09,4.192342e+06,1.031134e+02,1.039540e+02,1.296187e+00,3.634930e+00,3.597083e-01,3.341832e+00,1.155075
min,8.000000e+09,-1.229500e+02,-1.800000e+02,0.000000e+00,0.000000e+00,0.000000e+00,8.000000e-01,9.433981e-01,8.000000
25%,8.998750e+09,-6.111440e+01,-8.732040e+01,8.000000e+01,0.000000e+00,2.000000e+00,8.000000e-01,2.939388e+00,9.000000
50%,9.998750e+09,-5.227700e+01,4.949760e-04,1.600000e+02,1.000000e+00,6.000000e+00,1.520000e+00,6.053098e+00,10.000000
75%,1.100000e+10,-4.315925e+01,8.981450e+01,2.600000e+02,3.000000e+00,9.000000e+00,1.520000e+00,9.035486e+00,11.000000
max,1.200000e+10,8.000000e+09,1.800000e+02,3.400000e+02,4.000000e+00,1.100000e+01,3.000000e+00,1.150263e+01,12.000000

In [6]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3641386 entries, 0 to 3641385
Data columns (total 9 columns):
 #   Column               Dtype
---  ------               -----
 0   Frequency(Hz)        float64
 1   Magnitude(db)        float64
 2   Phase(degrees)       float64
 3   Angle of turn table  float64
 4   x                    float64
 5   y                    float64
 6   z                    float64
 7   Distance             float64
 8   Frequency(KHz)       float64
dtypes: float64(9)
memory usage: 250.0 MB

In [ ]:
#Deleting Extra columns
data= combined_df.drop( 'Frequency(KHz)', axis=1)
data= data.drop('Distance', axis=1)

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3641386 entries, 0 to 3641385
Data columns (total 7 columns):
 #   Column               Dtype
---  ------               -----
 0   Frequency(Hz)        float64
 1   Magnitude(db)        float64
 2   Phase(degrees)       float64
 3   Angle of turn table  float64
 4   x                    float64
 5   y                    float64
 6   z                    float64
dtypes: float64(7)
memory usage: 194.5 MB

In [15]:
# Checking for mising and null values
#data.isna()
#data.isnull()
#print(data.isnull().sum())
data[data.isnull().any(axis=1)]

,Frequency(Hz),Magnitude(db),Phase(degrees),Angle of turn table,x,y,z
150447,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Removing Null values
data=data.dropna()

In [ ]:
#converting Magnitude and Phase into Complex form
data['Magnitude_Lin']=10**(data['Magnitude(db)']/20)
data['Phase_rad']=np.deg2rad(data['Phase(degrees)'])
data['complex']=data['Magnitude_Lin']*np.exp(1j*data['Phase_rad'])

In [20]:
data.drop(columns=['Magnitude_Lin','Phase_rad'], inplace=True)
data.head()

,Frequency(Hz),Magnitude(db),Phase(degrees),Angle of turn table,x,y,z,complex
0,8.000000e+09,-22.42076,-70.99882,0.0,0.0,1.0,1.52,0.024639-0.071553j
1,8.001250e+09,-22.70777,-69.50725,0.0,0.0,1.0,1.52,0.025632-0.068584j
2,8.002500e+09,-22.54431,-75.13818,0.0,0.0,1.0,1.52,0.019136-0.072112j
3,8.003750e+09,-23.10117,-79.66623,0.0,0.0,1.0,1.52,0.012552-0.068840j
4,8.005000e+09,-22.74971,-87.64665,0.0,0.0,1.0,1.52,0.002992-0.072803j